export ZSH=~/.oh-my-zsh
# export TERM="tmux-256color"
export TERM="xterm-256color"
ZSH_THEME="powerlevel9k/powerlevel9k"
HYPHEN_INSENSITIVE="true"
DISABLE_AUTO_TITLE="true"
unsetopt correct_all
COMPLETION_WAITING_DOTS="true"
plugins=(git vi-mode)
export VIMRUNTIME=/usr/share/vim/vim80/
DISABLE_AUTO_UPDATE="true"
export SSLCERTFILE=~/Certs/server.crt
export SSLCACERTFILE=~/Certs/ca.crt
export SSLKEYFILE=~/Certs/server.key

stty -ixon

# alias vim='vimserver() { 
#   if [ $# -eq 0 ]; then 
#     vim --servername MAINVIMSERVER;
#   else 
#     vim --servername MAINVIMSERVER --remote $@; 
#   fi }; 
#   vimserver'

alias ll='ls -a'
alias bi='brew install'
alias bci='brew cask install'
# alias toclip='xclip -selection c'

bindkey -v
export KEYTIMEOUT=1
source $ZSH/oh-my-zsh.sh

POWERLEVEL9K_PROMPT_ON_NEWLINE=false
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context ssh dir dir_writable)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(vcs vi_mode)
POWERLEVEL9K_SHORTEN_DIR_LENGTH=4
POWERLEVEL9K_SHORTEN_STRATEGY="truncate_middle"

POWERLEVEL9K_ALWAYS_SHOW_CONTEXT=true

POWERLEVEL9K_VI_INSERT_MODE_STRING="INSERT"
POWERLEVEL9K_VI_COMMAND_MODE_STRING="NORMAL"

# Solarized-dark color config

#POWERLEVEL9K_DIR_HOME_FOREGROUND="white"
#POWERLEVEL9K_DIR_HOME_BACKGROUND="245"

#POWERLEVEL9K_DIR_DEFAULT_FOREGROUND="white"
#POWERLEVEL9K_DIR_DEFAULT_BACKGROUND="245"

#POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND="white"
#POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND="245"

#POWERLEVEL9K_VCS_CLEAN_FOREGROUND="white"
#POWERLEVEL9K_VCS_CLEAN_BACKGROUND="cyan"

#POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND="white"
#POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND="red"

#POWERLEVEL9K_VCS_MODIFIED_FOREGROUND="white"
#POWERLEVEL9K_VCS_MODIFIED_BACKGROUND="yellow"

POWERLEVEL9K_VI_MODE_INSERT_BACKGROUND='109'
POWERLEVEL9K_VI_MODE_INSERT_FOREGROUND='236'
POWERLEVEL9K_VI_MODE_NORMAL_BACKGROUND='245'
POWERLEVEL9K_VI_MODE_NORMAL_FOREGROUND='236'

POWERLEVEL9K_CONTEXT_DEFAULT_BACKGROUND='245'
POWERLEVEL9K_CONTEXT_DEFAULT_FOREGROUND='236'

POWERLEVEL9K_DIR_HOME_BACKGROUND='235'
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND='235'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND='235'
POWERLEVEL9K_DIR_HOME_FOREGROUND='214'
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND='214'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND='214'

POWERLEVEL9K_VCS_CLEAN_BACKGROUND='72'
POWERLEVEL9K_VCS_CLEAN_FOREGROUND='236'
# POWERLEVEL9K_VCS_CLEAN_BACKGROUND='235'
# POWERLEVEL9K_VCS_CLEAN_FOREGROUND='72'

POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='172'
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='236'
# POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='235'
# POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='172'

POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='124'
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='236'
# POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='235'
# POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='124'

POWERLEVEL9K_HOME_ICON=''
POWERLEVEL9K_HOME_SUB_ICON=''
POWERLEVEL9K_FOLDER_ICON=''

POWERLEVEL9K_TIME_BACKGROUND='235'
POWERLEVEL9K_TIME_FOREGROUND='214'

POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=''
POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR=''
POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=''
POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR=''
