export ZSH=/home/zsolt/.oh-my-zsh
# export TERM="tmux-256color"
export TERM="xterm-256color"
export PATH=$PATH:$HOME/google_define
ZSH_THEME="powerlevel9k/powerlevel9k"
HYPHEN_INSENSITIVE="true"
DISABLE_AUTO_TITLE="true"
unsetopt correct_all
COMPLETION_WAITING_DOTS="true"
plugins=(git ubuntu vi-mode)
export VIMRUNTIME=/usr/share/vim/vim80/

stty -ixon

alias vim='vimserver() { 
  if [ $# -eq 0 ]; then 
    vim --servername MAINVIMSERVER;
  else 
    vim --servername MAINVIMSERVER --remote $@; 
  fi }; 
  vimserver'

alias ll='ls -a'
alias svim='sudo vim'
alias cd..='cd ..'
alias toclip='xclip -selection c'
alias tmux='tmux -2'
alias backup='backup_configs'
alias goo='googler'
alias tmuxkillall='tmux kill-server'
alias tmuxkill='tmux kill-session -t '
alias tmuxattach='tmux attach-session -t '

bindkey -v
export KEYTIMEOUT=1
source $ZSH/oh-my-zsh.sh

POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir dir_writable vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status time root_indicator background_jobs root_indicator vi_mode)

POWERLEVEL9K_VI_INSERT_MODE_STRING="INSERT"
POWERLEVEL9K_VI_COMMAND_MODE_STRING="NORMAL"

# Solarized-dark color config

#POWERLEVEL9K_DIR_HOME_FOREGROUND="white"
#POWERLEVEL9K_DIR_HOME_BACKGROUND="245"

#POWERLEVEL9K_DIR_DEFAULT_FOREGROUND="white"
#POWERLEVEL9K_DIR_DEFAULT_BACKGROUND="245"

#POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND="white"
#POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND="245"

#POWERLEVEL9K_VCS_CLEAN_FOREGROUND="white"
#POWERLEVEL9K_VCS_CLEAN_BACKGROUND="cyan"

#POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND="white"
#POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND="red"

#POWERLEVEL9K_VCS_MODIFIED_FOREGROUND="white"
#POWERLEVEL9K_VCS_MODIFIED_BACKGROUND="yellow"
POWERLEVEL9K_DIR_HOME_BACKGROUND='09'
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND='09'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND='009'
POWERLEVEL9K_DIR_HOME_FOREGROUND='236'
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND='236'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND='236'

POWERLEVEL9K_TIME_BACKGROUND='235'
POWERLEVEL9K_TIME_FOREGROUND='214'

# `git hub colors`
POWERLEVEL9K_VCS_CLEAN_BACKGROUND='236'
POWERLEVEL9K_VCS_CLEAN_BACKGROUND='119'
POWERLEVEL9K_VCS_CLEAN_FOREGROUND='236'
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='214'
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='236'
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='196'
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='236'

# Quitar iconos del inicio
POWERLEVEL9K_HOME_ICON=''
POWERLEVEL9K_HOME_SUB_ICON=''
POWERLEVEL9K_FOLDER_ICON=''

# Vi-Mode
POWERLEVEL9K_VI_MODE_INSERT_BACKGROUND='005'
POWERLEVEL9K_VI_MODE_INSERT_FOREGROUND='236'
POWERLEVEL9K_VI_MODE_NORMAL_BACKGROUND='245'
POWERLEVEL9K_VI_MODE_NORMAL_FOREGROUND='236'

POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=''
POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR=''
POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=''
POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR=''
